---
apiVersion: v1
kind: Service
metadata:
  name: memcached-%SHARD_NUM%
  labels:
    app: memcached
    kubernetes.io/name: "memcached"
    role: shard-%SHARD_NUM%
    tier: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "metrics"
    prometheus.io/port: "9150"
spec:
  type: NodePort
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app: memcached
    role: shard-%SHARD_NUM%
