apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached-%SHARD_NUM%
  labels:
    app: memcached
    role: shard-%SHARD_NUM%
    tier: backend
    severity: opsgenie
spec:
  replicas: 1
  template:
    metadata:
      name: memcached-%SHARD_NUM%
      labels:
        app: memcached
        role: shard-%SHARD_NUM%
        tier: backend
        severity: opsgenie
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.35
        resources:
          limits:
            cpu: 200m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        ports:
          - containerPort: 11211
            protocol: TCP
        args:
          - -m 2047
          - -I 50M
      - name: memcached-exporter
        image: prom/memcached-exporter
        ports:
          - containerPort: 9150
            protocol: TCP

